BtoA/urls.py
from django.urls import path
from . import views


app_name= 'BtoA'

urlpatterns = [
    path('', views.survey, name='B_A'),
    path('<str:name>/', views.increaseSelectValue, name='increaseSelection'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('B-A/', include('BtoA.urls')),
    path('B-G/', include('BtoG.urls')),
    path('C-F/', include('CtoF.urls')),
    path('D-A/', include('DtoA.urls')),
    path('D-F/', include('DtoF.urls')),
    path('F-A/', include('FtoA.urls')),
    path('F-B/', include('FtoB.urls')),
    path('F-G/', include('FtoG.urls')),
    path('F-H/', include('FtoH.urls')),
    path('I-C/', include('ItoC.urls')),
    path('I-D/', include('ItoD.urls')),
    path('thanks/', include('ThankYou.urls')),
]

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>양서고등학교 설문조사</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #495E57;
        }
        #text {
            background-color: #F5F7F8;
            border: none;
            border-radius: 10px;
            padding: 1px;
            text-align: center;
        }
        .title {
            font-size: 30px;
            font-family: Arial, Helvetica, sans-serif;
        }
        .hello {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 18px;
        }
        #button {
            position: relative;
            margin-top: 20%;
        }
        #school {
            width: 50%;
        }
        #start {
            font-size: 80px;
            font-family: Arial, Helvetica, sans-serif;
            color: #000000;
            background-color: #F4CE14;
            padding: 20px 50px;
            border: none;
            border-radius: 10px;
            cursor: pointer;
        }
    </style>
    <script>
        function link() {
            window.location.href = "{% url 'BtoA:B_A' %}";
        }
    </script>
</head>
<body>
    <div id="text">
        <h1 class="title">양서고등학교의 이동 경로에 대한 설문조사</h1>
        <pre class="hello">
            ❤설문조사에 참여해 주셔서 감사합니다.❤
            이 설문조사는 창의연구주제탐를 위해 제작했습니다.
            이 설문조사는 「사람들이 이동할 때 어느 길로 가장 많이 가는지」에 대한 연구에 사용됩니다.
            다시 한 번 설문조사에 참여해 주셔서 감사합니다ㅠㅠ
            주변 사람에게도 이 사이트를 알려주세요😀👍
        </pre>
    </div>
    <div id="button">
        <button id="start" onclick="link()">START</button>
    </div>
</body>
</html>

templates/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>감사합니다.</title>
  <style>
    body {
        font-family: Arial, sans-serif;
        text-align: center;
        background-color: #f4f4f4;
        }
    #front {
        margin-top: 10%;
    }
    .thank {
        font-size: 300%;
    }
    #explain {
        margin-top: 2%;
    }
    .text {
        font-size: 150%;
    }
    .emoji {
        margin-top: 0px;
        font-size: 800%;
    }
  </style>
</head>
<body>
    <div id="front">
        <h1 class="thank">😁설문에 응해주셔서 감사합니다😁</h1>
    </div>
    <div id="explain">
        <H3 class="text">수고하셨어요!</h3>
        <p class="text">여러분이 참여하신 설문조사는 20522나무찬의 창의융합과제연구에 사용됩니다.<br>다시 한번 감사합니다</p>
    </div>
    <p class="emoji">🙇</p>

</body>
</html>